Tany
kuryuliya/ui-test-repo pull request #2
Opened 2021-07-11 08:54 UTC by tanykur

2021-07-11 13:56 UTC, kuryuliya requested changes

2021-07-11 13:56 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +    private final By search = By.xpath("//div[@class='flex header__search-container']//form[@class='search']//input[@type='search']");
можено использовать просто //input[@type='search']

2021-07-11 13:56 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +    private final By searchIcon = By.xpath("//button[@type='submit']");
для этой кнопки лучше использовать такой xpath //button[@class='search__btn']
почему:
1.Так посмотрев на локатор в коде нам будет лучше понятно, что это за элемент в dom, он более информативен
2. Выбирать атрибут сдледует принимая во внимание его потенциальное повторение для элементов. То есть скорее всего класс search__btn будет пирсвоен одному элементу, когда @type='submit' может быть присвоен к любой кнопке, которая что-то отправляет. Поэтому локатор с указанием класса, с большой вероятностью, будет более стабильным

2021-07-11 13:56 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +    private final By addToCart = By.xpath("//a[@ts-swap-push='.header_basket']//*[@class='header_basket-title t-bold']");
досточно написать такой икспас //*[@class='header_basket-title t-bold']

2021-07-11 13:56 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +        String productSearchText = driver.findElement(productSearch).toString();
.toString() тут использовать неправильно, нужно использовать метод getText()

2021-07-11 13:56 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +            Thread.sleep(5000);
не поняла что именно мы тут ждем

2021-07-11 13:56 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +        assertTrue(productAddCartText.contains("/product/11649387:675/") && productSearchText.contains("/product/11649387:675/"), "Items in the cart does not coincide with the selected");
какая-то сложная проверка, возможно нужно разбирть на две проверки

2021-07-12 18:08 UTC, tanykur commented on src/test/java/KastaTest.java
> +    private final By searchIcon = By.xpath("//button[@type='submit']");
fixed

2021-07-12 18:08 UTC, tanykur commented on src/test/java/KastaTest.java
> +    private final By addToCart = By.xpath("//a[@ts-swap-push='.header_basket']//*[@class='header_basket-title t-bold']");
fixed

2021-07-12 18:08 UTC, tanykur commented on src/test/java/KastaTest.java
> +        String productSearchText = driver.findElement(productSearch).toString();
fixed

2021-07-12 18:09 UTC, tanykur commented on src/test/java/KastaTest.java
> +            Thread.sleep(5000);
done

2021-07-12 18:09 UTC, tanykur commented on src/test/java/KastaTest.java
> +        assertTrue(productAddCartText.contains("/product/11649387:675/") && productSearchText.contains("/product/11649387:675/"), "Items in the cart does not coincide with the selected");
fixed

2021-07-12 18:11 UTC, closed without merging