Jeny selenium
kuryuliya/ui-test-repo pull request #5
Opened 2021-07-12 18:13 UTC by evgenres

2021-07-12 19:53 UTC, kuryuliya requested changes

2021-07-12 19:53 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +        var BasketLink = By.xpath("//*[@class='cart_pd-info']//a");
с мальенкой буквой переменные, эти и все остальные тоже

2021-07-12 19:53 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +    private final By typeTshort = By.xpath("//div[@class='flex header__search-container']//form[@class='search']//input[@type='search']");
очень длинный икспас, нужно сделать короче например
`//input[@class='search_input']`
и по его названию не понятно, что это поле поиска, нужно переименовать в searchField

2021-07-12 19:53 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +    private final By pressSerch = By.xpath("//button[@type='submit']");
выбрать другой атрибут, не type, такой икспас будет нестабильным.

2021-07-12 19:53 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +    private final By pressBuy = By.xpath("//*[@style='order:0']//*[text()='Купить']");
мы тут прописываем только локатор, еще не нажимаем ее. Поэтому переменная должна называться как имя существительно, например, buyButton, по названию переменной, мы должны описать для какого элмента этот локатор.
Остальные переменные с подобным именем тоже нужно переименовать

2021-07-12 19:53 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +
```
        var wait = new WebDriverWait(driver,Duration.ofSeconds(6));
        wait.until (ExpectedConditions.invisibilityOf(driver.findElement(closeWindow)));
```

2021-07-13 05:48 UTC, evgenres commented on src/test/java/KastaTest.java
> +        var BasketLink = By.xpath("//*[@class='cart_pd-info']//a");
готово

2021-07-13 05:50 UTC, evgenres commented on src/test/java/KastaTest.java
> +    private final By typeTshort = By.xpath("//div[@class='flex header__search-container']//form[@class='search']//input[@type='search']");
готово

2021-07-13 05:51 UTC, evgenres commented on src/test/java/KastaTest.java
> +    private final By pressSerch = By.xpath("//button[@type='submit']");
исправил

2021-07-13 05:53 UTC, evgenres commented on src/test/java/KastaTest.java
> +    private final By pressBuy = By.xpath("//*[@style='order:0']//*[text()='Купить']");
исправил

2021-07-13 06:00 UTC, evgenres commented on src/test/java/KastaTest.java
> +
done

2021-07-13 15:43 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +        var GetAtributeChoiseLink =driver.findElement(choisedItem).getAttribute("href");
c маленькой буквы

2021-07-13 15:43 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +        var GetAtributeBasketLink = driver.findElement(basketLinkItem).getAttribute("href");
с маленькой буквы

2021-07-14 06:32 UTC, evgenres commented on src/test/java/KastaTest.java
> +        var GetAtributeChoiseLink =driver.findElement(choisedItem).getAttribute("href");
готово

2021-07-14 06:32 UTC, evgenres commented on src/test/java/KastaTest.java
> +        var GetAtributeBasketLink = driver.findElement(basketLinkItem).getAttribute("href");
готово

2021-07-14 07:29 UTC, kuryuliya approved these changes

2021-07-14 07:30 UTC, merged