Jeny page object pattern
kuryuliya/ui-test-repo pull request #7
Opened 2021-07-18 10:01 UTC by evgenres

pull request

2021-07-18 19:34 UTC, kuryuliya requested changes

2021-07-18 19:34 UTC, kuryuliya commented on src/main/java/pages/MainPage.java
> +    public final By basket = By.xpath("//*[@href='/basket/']");
у вас повторяются с Таней локаторы, так как она смержила первая, ты теперь должне переиспользовать ее локаторы в своих тестаъ и удалить дубликаты

2021-07-18 19:34 UTC, kuryuliya commented on src/main/java/steps/MainSteps.java
> +    public void searchField() {driver.findElement(mainPage.searchField).sendKeys("220386025");
1.Тут не понятно что ты делаешь в этом шаге. Мы говорили, что степы должны описывать какое действие они выолняют. То есть метод должен например typeTextToSearchField. Это же касается и всех остальных методов, их нужно переименовать.
Если в классе уже есть такой метод, то ты должен его переиспользовать и не дублировать метод
2.Не правльно, когда в степе мы вводим в поле захардкожденное значение, ты должен передвать поисковый текст из теста, значит тебе его нужно передвать в метод как параметр

2021-07-18 19:34 UTC, kuryuliya commented on src/main/java/steps/MainSteps.java
> +    public void searchButton (){driver.findElement(mainPage.searchButton).click();
clickOnSearchButton, остальные переименовывать по аналогии

2021-07-18 19:34 UTC, kuryuliya commented on src/main/java/steps/MainSteps.java
> +        String getLink1 = driver.findElement(By.xpath("//*[@class='product__img']//a")).getAttribute("href");
1, By.xpath("//*[@class='product__img']//a" - локаторы должны быть прописаны в классе ...Page, а не степах
2, var вместо  String или сразу return
3.Какой именно атрибут(href в данном случае), тоже должно передваться из теста

2021-07-18 19:34 UTC, kuryuliya commented on src/main/java/steps/MainSteps.java
> +        return getLink;}
тоже самое

2021-07-18 19:34 UTC, kuryuliya commented on src/test/java/KastaTest.java
> +
удали кучу новых строк, допустима максимум одна пустая строка междку кодом

2021-07-20 06:57 UTC, evgenres commented on src/main/java/pages/MainPage.java
> +    public final By basket = By.xpath("//*[@href='/basket/']");
done

2021-07-20 06:57 UTC, evgenres commented on src/main/java/steps/MainSteps.java
> +    public void searchField() {driver.findElement(mainPage.searchField).sendKeys("220386025");
done

2021-07-20 06:57 UTC, evgenres commented on src/main/java/steps/MainSteps.java
> +    public void searchButton (){driver.findElement(mainPage.searchButton).click();
done

2021-07-20 06:57 UTC, evgenres commented on src/main/java/steps/MainSteps.java
> +        String getLink1 = driver.findElement(By.xpath("//*[@class='product__img']//a")).getAttribute("href");
done

2021-07-20 06:57 UTC, evgenres commented on src/main/java/steps/MainSteps.java
> +        return getLink;}
done

2021-07-20 06:57 UTC, evgenres commented on src/test/java/KastaTest.java
> +
done

2021-07-20 07:17 UTC, kuryuliya approved these changes

2021-07-20 07:18 UTC, merged